# Nukkit-MOT Server Properties
# For advanced settings, see nukkit-mot.yml
motd=§6Minecraft Bedrock Server §7- §eCustom Plugins
sub-motd=§7Join now!
server-port=19132
server-ip=0.0.0.0
view-distance=8
white-list=off
spawn-protection=0
max-players=20
allow-flight=on
spawn-animals=on
spawn-monsters=on
spawn-npcs=on
pvp=on
difficulty=2
gamemode=0
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon-password=
xbox-auth=off
language=eng
force-language=off
shutdown-message=§cServer closed
force-gamemode=on
hardcore=off
whitelist-reason=§cServer is white-listed
encryption=on
force-resources=off
force-resources-allow-client-packs=off
spawn-mobs=on
auto-save=on
rcon.password=zMWM1MjE2Z
rcon.port=25575
server-authoritative-movement=server-auth
server-authoritative-block-breaking=on
server-authoritative-inventory=on
